image: golang:1.11-stretch

stages:
  - test

vet:
  stage: test
  cache:
    paths:
      - $GOPATH/pkg/mod
  script:
    - go vet ./...

test:
  stage: test
  cache:
    paths:
      - $GOPATH/pkg/mod
  script:
    - go test all -race -v 
